### PR TITLE
Fixed previous next feature for content entries

### PR DESCRIPTION
**Pull request by bbucek**
It used to show first record for previous or last for next. 
It didn't show up in test with only 3 entries, but was clear with four.

### CODE REVIEW

**Comment by did** [comment]
@bbucek thanks! Unfortunately, your patch breaks some local sites I've got for testing purpose. However, there is something wrong in the current implementation according to your modified spec.
I'm investigating at it right now.

**Comment by bbucek** [comment]
Hi @did. 
Let me know if I can help somehow. I'm more than happy to investigate it further. 
If you can give me more details in what situations it breaks, I will try to help out. 
It fixes the issue in the most trivial situation and it seems that I'm not the only person struggling with it (https://locomotive-v3.readme.io/discuss/56b1c6f2f48f270d00e0dddd), but I'm aware that it can break in more complex examples.

**Comment by did** [comment]
fixed :-) let me know if it worked for you as well. Thanks again!

**Comment by bbucek** [comment]
Just checked, but it still doesn't work as intended.
Next works OK now in every case, but previous always shows first, unless it's first item, when it correctly returns nil.
Just to clarify I'm testing on wagon and content_type defined with `order_by: manually` and `order_direction: asc`. The example I have is navigation to previous and next item on content_type_template page.

**Comment by did** [comment]
@bbucek I added another spec for the previous method to describe the issue. Now, it should work for good :-)

**Comment by bbucek** [comment]
Sweet! Works like a charm now! Thanks a lot.

**Pull request closed without merging**
