### PR TITLE
omit with_scope conditions when passed value is nil

### PR DESCRIPTION
**Pull request by dahogenelst**
github issue: https://github.com/locomotivecms/steam/issues/183

### CODE REVIEW

**Comment by did** [comment]
hey @dahogenelst! thanks for the PR. What happens if I do want to request all content entries with a specific field set to null?

**Comment by dahogenelst** [comment]
I dunno, shall I spec it out to find you an answer or was it a rhetorical question? :)

**Comment by did** [comment]
it wasn't at all. This case might happen, ie, "I want to retrieve all my content entries which have the value of the field C4 equals to null". 
I don't see an elegant way to address the 2 cases (yours and mine).
Thanks for your help btw!

**Comment by dahogenelst** [comment]
Agreed on the case filtering on null must be possible. Closing issue

**Pull request closed without merging**
